from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class TimelinePoint(BaseModel):
    date: str
    units: int


class DemandForecastData(BaseModel):
    product_id: str
    product_title: str
    has_sufficient_data: bool
    message: str
    historical_sales_total: int
    predicted_demand_units: Optional[int] = None
    predicted_demand_daily_rate: Optional[float] = None
    trend: str
    trend_slope: float
    confidence: str
    confidence_reason: str
    forecast_days: int
    historical_timeline: List[TimelinePoint] = Field(default_factory=list)


class ProductMarketingMetric(BaseModel):
    product_id: str
    title: str
    sku: str
    category_name: str
    price: float
    stock_quantity: int
    views: int
    cart_additions: int
    add_to_cart_rate: float
    conversion_rate: float
    units_sold: int
    revenue: float
    average_selling_price: float
    stock_velocity: float
    demand_forecast: Optional[DemandForecastData] = None


class MarketingInsightItem(BaseModel):
    id: str
    product_id: str
    product_title: str
    insight_type: str
    severity: str = Field(..., description="urgent, high, medium, positive, warning, info")
    metric: str = Field(..., description="Concrete data metric observation")
    finding: str = Field(..., description="Explainable data finding")
    suggested_action: str = Field(..., description="Actionable recommendation based on finding")
    observation_data: Dict[str, Any] = Field(default_factory=dict)


class MarketingInsightsResponse(BaseModel):
    seller_id: str
    generated_at: str
    total_products_analyzed: int
    insights_count: int
    insights: List[MarketingInsightItem]
    product_metrics: List[ProductMarketingMetric]


class PersonalizedOfferItem(BaseModel):
    id: str
    title: str
    badge: str
    description: str
    suggested_product_id: str
    suggested_product_title: str
    suggested_product_price: float
    promo_code: str
    discount_percent: int
    reason: str
    is_ai_generated: bool = True


class PersonalizedOffersResponse(BaseModel):
    user_id: Optional[str] = None
    total_offers: int
    generated_at: str
    offers: List[PersonalizedOfferItem]
    notice: str = "All offers are personalized recommendations generated by CortexPulse AI without external communication dispatch."
