from typing import Optional, List, Dict, Any
from fastapi import APIRouter, Query, Depends, status
from app.core.auth import get_current_user, AuthUser, security
from fastapi.security import HTTPAuthorizationCredentials
from app.schemas.ml import (
    RecommendationResponse,
    CustomerSegmentationResponse,
)
from app.services.ml_service import MLService

router = APIRouter()


async def get_optional_user(
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(security),
) -> Optional[AuthUser]:
    """Retrieve authenticated user if bearer token is present, else None."""
    if not credentials:
        return None
    try:
        return await get_current_user(credentials)
    except Exception:
        return None


@router.get(
    "/recommendations/personalized",
    response_model=RecommendationResponse,
    summary="Get Personalized Product Recommendations",
)
async def get_personalized_recommendations(
    user_id: Optional[str] = Query(None, description="Optional customer user ID"),
    session_id: Optional[str] = Query(None, description="Optional guest session token"),
    limit: int = Query(8, ge=1, le=24, description="Number of items to recommend"),
    optional_user: Optional[AuthUser] = Depends(get_optional_user),
) -> RecommendationResponse:
    """
    Returns personalized product recommendations powered by scikit-learn content-based
    filtering combined with the user's interaction history (views, carts, wishlist, purchases).
    Falls back to trending items if interaction history is sparse.
    """
    resolved_user_id = user_id or (optional_user.id if optional_user else None)
    return MLService.get_personalized_recommendations(
        user_id=resolved_user_id,
        session_id=session_id,
        limit=limit,
    )


@router.get(
    "/seller/analytics/customer-segments",
    response_model=CustomerSegmentationResponse,
    summary="Get AI Customer Segmentation",
)
@router.get(
    "/segmentation/customers",
    response_model=CustomerSegmentationResponse,
    summary="Get AI Customer Segmentation (Alias)",
)
async def get_customer_segmentation(
    optional_user: Optional[AuthUser] = Depends(get_optional_user),
) -> CustomerSegmentationResponse:
    """
    Trains an unsupervised scikit-learn KMeans clustering model on real purchase history
    and interaction behaviors. Categorizes shoppers into ML-derived customer segments:
    High Value, Frequent Buyer, Occasional Buyer, New Customer, and Low Engagement.
    """
    return MLService.get_customer_segmentation()


@router.get(
    "/offers/personalized",
    summary="Get AI Personalized In-App Marketing Offers",
)
async def get_personalized_offers(
    user_id: Optional[str] = Query(None, description="Optional customer user ID"),
    session_id: Optional[str] = Query(None, description="Optional guest session ID"),
    optional_user: Optional[AuthUser] = Depends(get_optional_user),
) -> Dict[str, Any]:
    """
    Returns personalized in-app promotional offers based on customer interaction history
    and RFM segmentation (category affinity, repeat buyer reward, exploration nudges).
    Offers are displayed strictly within the application (no real emails/SMS) and clearly
    marked as AI-generated.
    """
    from datetime import datetime, timezone
    from app.services.marketing_insights_service import MarketingInsightsService
    resolved_user_id = user_id or (optional_user.id if optional_user else None)
    offers = MarketingInsightsService.get_personalized_in_app_offers(
        user_id=resolved_user_id,
        session_id=session_id,
    )
    return {
        "user_id": resolved_user_id,
        "total_offers": len(offers),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "offers": offers,
        "notice": "All promotional offers are generated by CortexPulse AI personalization engine. No external SMS or email dispatch is executed.",
    }

